import type { Metadata } from "next";
import "./globals.css";
import { NavbarDemo } from "@/components/navbar/NavbarDemo";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth font-sans"
      suppressHydrationWarning
    >
      <body className="antialiased">
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
