import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/navbar/NavbarDemo";
import Footer from "@/components/footer/footer";

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bebasNeue.className} scroll-smooth`} suppressHydrationWarning>
      <body className="antialiased">
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
