import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/navbar/NavbarDemo";
import Footer from "@/components/footer/footer";

const outfit = Outfit({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.className} scroll-smooth`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
